### ISSUE TITLE
[Weapon name] "0" should be "stick" ?

### ISSUE THREAD

**Issue by challsted** [delayel06/adventureroad#10]
Im currently wielding a stick :sweat_smile: 

"You hit the bear in the nose with your **0**. You inflict 2 damage to him, reduced by his 0 defense points."

**Comment by delayel06** [comment]
That shouldn't be possible.. you should have picked up a weapon in the prison

**Comment by challsted** [comment]
Right! I picked up a book and became a mage(wizard?). 

Im not sure haw it happened, but it didn't happen again after that 1once.

**Comment by challsted** [comment]
Right! I picked up a book and became a mage(wizard?). 

Im not sure haw it happened, but it didn't happen again after that once.

**Comment by delayel06** [comment]
It has been fixed, thank you for your help.
